// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    'IEp:arrowLeft': typeof import('~icons/ep/arrow-left')['default']
    InButton: typeof import('./src/components/InButton.vue')['default']
    InContainer: typeof import('./src/components/container/InContainer.vue')['default']
    InCopyTag: typeof import('./src/components/InCopyTag.vue')['default']
    InDialog: typeof import('./src/components/InDialog.vue')['default']
    InFilterContainer: typeof import('./src/components/container/InFilterContainer.vue')['default']
    InFilterItem: typeof import('./src/components/container/InFilterItem.vue')['default']
    InFullscreen: typeof import('./src/components/InFullscreen.vue')['default']
    InIcon: typeof import('./src/components/InIcon.vue')['default']
    InIconCollection: typeof import('./src/components/InIconCollection.vue')['default']
    InQrcode: typeof import('./src/components/qrcode/InQrcode.vue')['default']
    'ITabler:arrowRight': typeof import('~icons/tabler/arrow-right')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Verify: typeof import('./src/components/verifition/Verify.vue')['default']
    VerifyPoints: typeof import('./src/components/verifition/verify/VerifyPoints.vue')['default']
    VerifySlide: typeof import('./src/components/verifition/verify/VerifySlide.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
